services:
  AAA:
    image: hoh
    ports:
      - "8080:8080"
    environment:
      - "AAA_ENV=dev"
    container_name: hoh
    networks:
      - new-net

    volumes:
      - Z:\Coding\Projects\Python\docker learn\names.txt:/AAA/names.txt

  # # new containter:
  # BBB                               # build from an existing Dockerfile
  #   build: ./(path to a docker file)             

  # networks:
  #   new-net:


docker-compose (up/down)             # to run/stop
