FROM python

WORKDIR /main

# COPY . .                          # copy all in current dir
COPY ./main.py .
COPY ./names.txt .

# RUN pip install (Py library)

CMD [ "python", "main.py" ]

# PULL
# EXPOSE (port No.)
