apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce                                   # ReadWriteOnce, ReadOnlyMany, ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle              # Recycle, Retain, Delete
  storageClassName: standard   
  hostPath:                                           # HostPath, emptyDir, NFS, Ceph, etc 
    path: /xyz/xyz                   
    type: DirectoryOrCreate                           # DirectoryOrCreate, Directory, FileOrCreate, File     
  mountOptions:                                  # ?
    - hard                                       # ?
    - nfsvers=4.1                                # ?
  nfs:                                           # ?
    path: /tmp                 
    server: 172.17.0.2                           



Have storage  ->  Make PV  ->  Make PVC  ->  Use PVC in Pod