apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  VolumeName: database-pv                                    # Name of PV
  StorageClassName: standard  
  accessModes:
    - ReadWriteOnce                             
  resources:                                                 # Resource request
    requests:                                                # Requested resources  
      storage: 3Gi